
          # -*- coding: utf-8 -*-
"""Estatística descritiva usando Pandas e Numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aBFFPQ-n-ohA1X-Y1KdFahGcVwpH-pkn
"""

import numpy as np
import pandas as pd


df = pd.read_csv('/content/drive/MyDrive/PUC -IA -  AED/dados.csv')

print(df.head())

df['Nota Total'] = df.sum(axis=1)

print(df.head())

df['Desvio Padrao'] = df.std(axis=1)
df['Variancia'] = df.var(axis=1)
print(df.head())

df_medias_questoes = pd.DataFrame(columns=['Questao', 'Media'])
for i in range(1, 18):
    coluna = f'Questao {i}'
    media_questao = df[coluna].mean()
    df_medias_questoes = df_medias_questoes.append({'Questao': coluna, 'Media': media_questao}, ignore_index=True)

print(df_medias_questoes.head())

# Calcular a média da nota total
nota_media = df['Nota Total'].mean()
nota_media = round(nota_media, 2)
# Exibir a média da nota total
print("Média da Nota Total:", nota_media)

# Qual a Questão que teve a maior média pontos?

df_ordenado = df_medias_questoes.sort_values('Media')
# Obter o maior valor da coluna 'Coluna 1'
maior_valor = df_ordenado['Media'].max()

# Obter o menor valor da coluna 'Coluna 1'
menor_valor = df_ordenado['Media'].min()

# Exibir o maior e o menor valor
print("Maior valor:", maior_valor)
print("Menor valor:", menor_valor)

# Obter a linha correspondente ao maior valor
linha_maior_valor = df_ordenado.loc[df_ordenado['Media'] == maior_valor, 'Questao'].values[0]

# Obter a linha correspondente ao menor valor
linha_menor_valor = df_ordenado.loc[df_ordenado['Media'] == menor_valor, 'Questao'].values[0]

# Exibir o maior e o menor valor com suas respectivas colunas 'Questao'
print("Maior valor:", maior_valor, "na", linha_maior_valor)
print("Menor valor:", menor_valor, "na", linha_menor_valor)

print(df_ordenado)

